language: r
sudo: false
cache: packages

r:
 - release
 - devel
 - oldrel

env:
  global:
    secure: "rhBMkx3pwZyJnO3P19UDag2uL4PFr1skLsjqYdYwD8uWt4reZU4A2CJVqvGcWTIEKZ8YB6dC8ASmE3nVy6XHZKCfkieiHEirVKocuHrpZHNMMpcW9R/FBmBuGUsYiZGeIBgT8YHNda1/2/urncnKUGDzrjQndnKhXX5XMmGHuXaJRbNINkmxGIIwRBWl3ol1/DNIjBaNpwSRuT7+tuLyF3Hra0ogJC9YAkWguFn0gBBXSiJON8PoBlxr+NJ4DsgpfvGR2gM2NweZQIOG1nfeesyvCaM7RQ03XDFD7ZdFem/NJiKrwFgO/RaudJedEYPIH6UoqpDgLiiDR+2P56a9qsKAkjNj+qZZYS+/pdJ85dZ/kGxAc8C/Cq1mLi/t8k7SpKWnpiR3RstlxQvPgUMQWMD7IHipH4WfhgCoi+2KCY4XUFF61By+xtmgRGy37in0ENAAdYWltqXY2I+KZ/42wuI9NXH8y50LU08W3vLreNplf8ekR2JxhRAS+KklNCcIIVxo2nXn22lFlm6wk9l26e4bOmR/USzAJSsRpt+Okf4jlLYUoXI561Fo4YMgh3vpBmxYyNpU77idHGnDq2FNpZQ75YIgS/oFa7lcrDzhsU/ywRAakA0YknPRfRFuD5ZGHaI6BebAbVMncSxdkdB2idzHgjlq98njLORD1EN/yMA="

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
